---
controllers:
  garage_doors:
    trigger_time: 100
    force_time: 14500
    gpio_pins:
      physical: 
        - 7
        - 11
      bcm: 
        - 4
        - 17
endpoints:
  host: "localhost:8080"
  paths: 
    control: "/control"
    monitor: "/monitor"
